version: '3'

services:
  db:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=test
    ports:
      - 5432:5432

  api:
    container_name: api
    build: .
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - db